//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp9
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_insertion
    {
        public int no { get; set; }
        public string Sname { get; set; }
        public string mobno { get; set; }
        public string purchase { get; set; }
        public string discount { get; set; }
        public string amount { get; set; }
    }
}
